# Generated by Django 2.1 on 2019-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('Transaction_Type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('DebitAmount', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CreditAmount', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
